/**
 * The Lab's glossary. Every term has an anchor `#term-<id>`; other tabs link here with <Term>.
 * Plain language first, then a formula where it helps, then how it shows up in *this* model.
 */
export type GlossaryEntry = {
  id: string;
  term: string;
  category: "Metrics" | "Uncertainty" | "Trees & boosting" | "Training protocol" | "Explainability" | "Fantasy";
  short: string;
  body: string;
  formula?: string;
  here?: string;
  related?: string[];
};

export const GLOSSARY: GlossaryEntry[] = [
  // ---------------------------------------------------------------- metrics
  {
    id: "mae",
    term: "MAE (mean absolute error)",
    category: "Metrics",
    short: "The average size of a miss, in points.",
    body: "Take every prediction, subtract the actual score, drop the sign and average. An MAE of 20 means a typical prediction is about 20 fantasy points off. It treats a 10-point miss on a bowler the same as a 10-point miss on a batter, and large misses count linearly (unlike RMSE).",
    formula: "MAE = (1/n) · Σ |actualᵢ − predictedᵢ|",
    here: "Reported per player-match row, then averaged per match; compared with the last-5 baseline. Lower is better.",
    related: ["rmse", "baseline", "residual"],
  },
  {
    id: "rmse",
    term: "RMSE (root mean squared error)",
    category: "Metrics",
    short: "Like MAE but large misses are punished more.",
    body: "Square each error, average, then take the square root. Because errors are squared, one 80-point miss hurts much more than four 20-point misses. The mean head of our model is trained to minimise squared error (its training curve is in L2 / RMSE units).",
    formula: "RMSE = √[ (1/n) · Σ (actualᵢ − predictedᵢ)² ]",
    here: "The mean head's learning curves report l2 (mean squared error) on the inner validation season.",
    related: ["mae", "loss-function"],
  },
  {
    id: "spearman",
    term: "Spearman rank correlation (ρ)",
    category: "Metrics",
    short: "Does the model order players correctly within a match?",
    body: "Rank the players of one match by prediction and by actual points, then correlate the two rankings. +1 means a perfect order, 0 means no relationship. For fantasy picking the order matters more than the exact number: you only need to know who will outscore whom.",
    formula: "ρ = Pearson correlation of rank(predicted) and rank(actual), computed within each match, then averaged over matches",
    here: "Computed per match (22–24 players), averaged across matches.",
    related: ["mae", "best-xi-points"],
  },
  {
    id: "best-xi-points",
    term: "Best-XI points",
    category: "Fantasy",
    short: "The real score of the team an optimiser picks from the predictions.",
    body: "For each match an exact optimiser picks the 11 players (Dream11 rules: 1–8 per role, max 10 from one side, C ×2, VC ×1.5) that maximise the predicted points. That team is then scored with the players' actual points. It is the metric closest to what a user experiences.",
    here: "Model XI vs baseline XI vs the hindsight XI (the best team possible with actual points, an upper bound).",
    related: ["hindsight-xi", "captain-hit-rate", "baseline"],
  },
  {
    id: "hindsight-xi",
    term: "Hindsight (perfect) XI",
    category: "Fantasy",
    short: "The best possible team, picked after the match with actual points.",
    body: "An upper bound nobody can reach before the match. The gap between the model's XI and the hindsight XI shows how much of the attainable score the model captures.",
    related: ["best-xi-points"],
  },
  {
    id: "captain-hit-rate",
    term: "Captain hit rate (top-2)",
    category: "Fantasy",
    short: "How often the chosen captain is one of the match's top-2 scorers.",
    body: "The captain doubles their points, so picking the right one is the single biggest lever in fantasy. We count a hit when the optimiser's captain finished first or second in actual points among all players in the match.",
    related: ["best-xi-points"],
  },
  {
    id: "baseline",
    term: "Baseline (last-5 form)",
    category: "Metrics",
    short: "The simple rule the model must beat: a player's average over their last 5 games.",
    body: "A model is only useful if it beats an obvious, cheap rule. Ours predicts each player's points as the mean of their last 5 IPL games (0 for debutants). Every metric is shown as model vs baseline, with a confidence interval on the difference.",
    related: ["bootstrap-ci", "mae"],
  },
  {
    id: "bootstrap-ci",
    term: "Paired bootstrap 95% confidence interval",
    category: "Metrics",
    short: "A range for 'how much better than the baseline', accounting for luck.",
    body: "Take the per-match differences (model − baseline). Resample the matches with replacement thousands of times and recompute the average difference each time; the middle 95% of those averages is the interval. 'Paired' means both methods are judged on the same matches, which removes match-to-match noise. If the interval excludes 0, the improvement is unlikely to be luck.",
    formula: "CI₉₅ = [2.5th, 97.5th] percentile of mean(d*) over B resamples d* of the per-match differences d",
    here: "2,000 resamples over matches.",
    related: ["baseline"],
  },
  {
    id: "residual",
    term: "Residual",
    category: "Metrics",
    short: "Actual minus predicted for one row.",
    body: "Positive residual = the player scored more than predicted (model under-predicted). Looking at residuals by group (role, experience, batting first) reveals systematic bias that one overall number hides.",
    formula: "residual = actual − predicted;   bias = mean(residual)",
    related: ["mae", "calibration"],
  },
  // ---------------------------------------------------------------- uncertainty
  {
    id: "quantile",
    term: "Quantile (p10 / p50 / p90)",
    category: "Uncertainty",
    short: "A value the outcome should fall below a given share of the time.",
    body: "The 10th percentile (p10) is a 'floor': the player should score less than it only 10% of the time. p50 is the median and p90 a 'ceiling'. Fantasy scores are very skewed (many low scores, a few huge ones), so a range says much more than a single number.",
    here: "Three separate LightGBM heads predict p10, p50 and p90 directly; they are sorted so they never cross.",
    related: ["pinball-loss", "coverage", "calibration"],
  },
  {
    id: "pinball-loss",
    term: "Pinball (quantile) loss",
    category: "Uncertainty",
    short: "The loss that teaches a model to predict a quantile.",
    body: "For the 90th percentile, under-predicting costs 0.9 per point and over-predicting costs only 0.1 per point, so the best constant is the value exceeded 10% of the time. Lower pinball loss = sharper and better-calibrated quantiles.",
    formula: "Lτ(y, q) = τ·(y − q) if y ≥ q, else (1 − τ)·(q − y)",
    related: ["quantile", "loss-function"],
  },
  {
    id: "coverage",
    term: "Coverage (p10–p90)",
    category: "Uncertainty",
    short: "How often the actual score lands inside the predicted range.",
    body: "A p10–p90 interval should contain the actual score 80% of the time. Much less means the ranges are over-confident (too narrow); much more means they are too wide to be useful.",
    formula: "coverage = share of rows with p10 ≤ actual ≤ p90   (target 80%)",
    related: ["quantile", "calibration"],
  },
  {
    id: "calibration",
    term: "Calibration",
    category: "Uncertainty",
    short: "Do predicted numbers mean what they say on average?",
    body: "Group predictions into bins (e.g. all rows predicted 30–35 points) and compare with the actual average in each bin. A calibrated model's bins lie on the diagonal. For quantiles, calibration means the share of actuals below p10 is about 10%, below p50 about 50%, below p90 about 90%.",
    related: ["coverage", "reliability-diagram"],
  },
  {
    id: "reliability-diagram",
    term: "Reliability diagram",
    category: "Uncertainty",
    short: "Predicted vs actual average per prediction bin; the diagonal is perfect.",
    body: "Points above the diagonal: players in that bin scored more than predicted (under-prediction). Below: over-prediction. Bigger bins (more rows) are more trustworthy.",
    related: ["calibration"],
  },
  // ---------------------------------------------------------------- trees & boosting
  {
    id: "decision-tree",
    term: "Decision tree",
    category: "Trees & boosting",
    short: "A flowchart of yes/no questions on features that ends in a number.",
    body: "Each internal node asks something like 'ewm_5 < 31.2?'; each leaf holds a value. A row follows the answers to one leaf and receives its value. A single small tree is a weak, coarse model.",
    related: ["leaf", "gradient-boosting"],
  },
  {
    id: "leaf",
    term: "Leaf",
    category: "Trees & boosting",
    short: "An end node of a tree; it stores the value added to the prediction.",
    body: "num_leaves caps how many leaves one tree may have, i.e. how many distinct groups of rows it can separate. More leaves = more complex trees.",
    related: ["decision-tree", "num-leaves"],
  },
  {
    id: "gradient-boosting",
    term: "Gradient boosting",
    category: "Trees & boosting",
    short: "Many small trees, each one fixing the errors left by the ones before.",
    body: "Start from a constant (e.g. the average score). Fit a small tree to the current errors (more precisely, the negative gradient of the loss), add a fraction of it (the learning rate) to the model, repeat hundreds of times. LightGBM is a fast implementation that grows trees leaf-wise and bins feature values into histograms.",
    formula: "F₀ = const;  Fₘ(x) = Fₘ₋₁(x) + η · treeₘ(x),   treeₘ fit to −∂L/∂F at Fₘ₋₁",
    here: "Four independent boosted models ('heads'): mean (squared error) and p10/p50/p90 (pinball loss).",
    related: ["learning-rate", "decision-tree", "early-stopping"],
  },
  {
    id: "loss-function",
    term: "Loss function",
    category: "Trees & boosting",
    short: "The number training tries to make small.",
    body: "Squared error for the mean head (it targets the average outcome), pinball loss for each quantile head (it targets that quantile). Learning curves plot the loss per boosting round.",
    related: ["rmse", "pinball-loss"],
  },
  {
    id: "learning-rate",
    term: "Learning rate (η, shrinkage)",
    category: "Trees & boosting",
    short: "How much of each new tree is added; smaller = slower but steadier.",
    body: "With η = 0.03 each tree corrects only 3% of the remaining error, so the model needs many trees but each step is cautious, which usually generalises better. Learning rate and number of trees trade off against each other.",
    related: ["gradient-boosting", "early-stopping"],
  },
  {
    id: "num-leaves",
    term: "num_leaves",
    category: "Trees & boosting",
    short: "Maximum leaves per tree: the main knob for tree complexity.",
    body: "A tree with 15 leaves can model interactions between a few features; 255 leaves can memorise noise. Too many leaves with little data overfits.",
    related: ["leaf", "overfitting"],
  },
  {
    id: "min-child-samples",
    term: "min_child_samples",
    category: "Trees & boosting",
    short: "Minimum rows a leaf must contain.",
    body: "A leaf built from 5 rows is a guess; one built from 100 rows is an average you can trust. Larger values make the model smoother and less prone to fitting flukes.",
    related: ["overfitting", "regularisation"],
  },
  {
    id: "feature-fraction",
    term: "feature_fraction",
    category: "Trees & boosting",
    short: "Each tree sees a random subset of the features.",
    body: "At 0.8 each tree may only use 80% of the features. This decorrelates the trees and stops the model leaning on one dominant feature, much like a random forest.",
    related: ["bagging", "regularisation"],
  },
  {
    id: "bagging",
    term: "Bagging (bagging_fraction / bagging_freq)",
    category: "Trees & boosting",
    short: "Each tree is trained on a random subset of the rows.",
    body: "bagging_fraction 0.8 with bagging_freq 1 means every iteration samples 80% of the rows. The noise this adds acts as regularisation and speeds training.",
    related: ["feature-fraction", "regularisation"],
  },
  {
    id: "regularisation",
    term: "Regularisation (lambda_l2 …)",
    category: "Trees & boosting",
    short: "Anything that discourages the model from fitting noise.",
    body: "lambda_l2 adds a penalty on large leaf values, shrinking them toward zero; min_child_samples, feature/bagging fractions, a small learning rate and early stopping are also regularisers.",
    formula: "leaf value = −Σgradients / (Σhessians + λ₂)",
    related: ["overfitting", "min-child-samples"],
  },
  {
    id: "overfitting",
    term: "Overfitting",
    category: "Trees & boosting",
    short: "Learning the training data's noise instead of the pattern.",
    body: "Training loss keeps falling while validation loss stalls and then rises. The model 'knows' past matches by heart but predicts new ones worse. Visible in the learning curves as the gap between the two lines.",
    related: ["early-stopping", "regularisation"],
  },
  {
    id: "early-stopping",
    term: "Early stopping",
    category: "Trees & boosting",
    short: "Stop adding trees when the validation loss stops improving.",
    body: "Train while watching a held-out validation set; if the validation loss hasn't improved for N rounds, stop and keep the best round. That number of trees is then used to refit on all the training data.",
    here: "Validation = the last ~one season of the training window (never the season being scored); patience = early_stopping_rounds.",
    related: ["overfitting", "learning-rate"],
  },
  {
    id: "parameters",
    term: "Learned parameters (trees vs neural nets)",
    category: "Trees & boosting",
    short: "The numbers a model sets during training.",
    body: "A neural network's parameters are its weights and biases, all updated together by gradient descent. A tree ensemble's 'parameters' are the split thresholds and leaf values it chose; each tree is fixed once added. We count one threshold per internal node plus one value per leaf. Hyper-parameters (num_leaves, learning rate, …) are chosen by us, not learned.",
    formula: "per tree: leaves + (leaves − 1) split thresholds",
    related: ["hyperparameter", "decision-tree"],
  },
  {
    id: "hyperparameter",
    term: "Hyper-parameter",
    category: "Trees & boosting",
    short: "A setting chosen before training (not learned from the data).",
    body: "num_leaves, min_child_samples, learning_rate, etc. They are tuned by trying a small grid and keeping the setting with the best validation error across the cross-validation folds.",
    related: ["cross-validation", "parameters"],
  },
  // ---------------------------------------------------------------- protocol
  {
    id: "cross-validation",
    term: "Cross-validation",
    category: "Training protocol",
    short: "Estimate performance on data the model didn't train on, several times.",
    body: "Split the data into folds, train on some and score on the others, repeat. For time-ordered data the folds must respect time, so we use rolling-origin folds.",
    related: ["rolling-origin", "data-leakage"],
  },
  {
    id: "rolling-origin",
    term: "Rolling-origin (time-series) CV",
    category: "Training protocol",
    short: "Train on seasons before Y, validate on Y; slide Y forward.",
    body: "Fold 2020 trains on 2008–2019 and scores 2020, fold 2021 trains on 2008–2020 and scores 2021, and so on. The model never sees the future, exactly like in real use.",
    here: "Folds 2020–2024 choose the hyper-parameters. 2025 is then scored once as a test; 2026 is walk-forward.",
    related: ["cross-validation", "walk-forward", "test-set"],
  },
  {
    id: "test-set",
    term: "Test set (held-out season)",
    category: "Training protocol",
    short: "Data used exactly once, after every choice was made.",
    body: "If you keep checking the test set while tuning, it stops being an honest estimate. Our 2025 season is scored once, by a model trained on 2008–2024 with the chosen settings.",
    related: ["rolling-origin"],
  },
  {
    id: "walk-forward",
    term: "Walk-forward evaluation",
    category: "Training protocol",
    short: "Replay a season: retrain, predict the next block of matches, repeat.",
    body: "Mimics live use. Before each block of matches the model is retrained on everything played so far, then predicts the block. It shows whether recent data helps and how the model behaves as a season unfolds.",
    here: "2026, retraining every wf_block matches.",
    related: ["rolling-origin"],
  },
  {
    id: "data-leakage",
    term: "Data leakage",
    category: "Training protocol",
    short: "Information from the future sneaking into a prediction.",
    body: "E.g. using a player's season average that includes the match being predicted. Leakage makes offline metrics look great and live predictions disappoint. Our features are point-in-time: each is computed only from matches that finished before the toss of the match being predicted.",
    here: "A test perturbs every outcome from a cut-off match onward and requires the features at that match to stay identical.",
    related: ["point-in-time"],
  },
  {
    id: "point-in-time",
    term: "Point-in-time feature",
    category: "Training protocol",
    short: "A feature computed only from what was known at prediction time.",
    body: "At the toss we know both XIs, the venue, the toss result and weather, plus every past match. We don't know this match's scorecard. Every feature respects that cut-off.",
    related: ["data-leakage"],
  },
  {
    id: "recency-weighting",
    term: "Recency weighting",
    category: "Training protocol",
    short: "Recent seasons count more in training.",
    body: "Cricket changes (impact player rule, scoring rates), so a 2010 match should teach the model less than a 2024 one. Each training row gets a weight that halves every few seasons back.",
    formula: "weight = 0.5 ^ ((newest season − season) / half-life)",
    related: ["walk-forward"],
  },
  {
    id: "inner-validation",
    term: "Inner validation",
    category: "Training protocol",
    short: "A validation slice carved out of the training window.",
    body: "Used for early stopping, so the number of trees is chosen without ever peeking at the fold being scored. Here: the last ~74 matches (about one season) before the fold.",
    related: ["early-stopping"],
  },
  // ---------------------------------------------------------------- explainability
  {
    id: "feature-importance",
    term: "Feature importance (gain / split)",
    category: "Explainability",
    short: "How much the trees rely on each feature.",
    body: "Split importance counts how many times a feature is used in a split. Gain importance sums how much those splits reduced the loss, so it weighs useful splits more. Both are global and say nothing about the direction of the effect; correlated features share credit.",
    related: ["shap"],
  },
  {
    id: "shap",
    term: "SHAP values",
    category: "Explainability",
    short: "How much each feature pushed one prediction up or down.",
    body: "From game theory (Shapley values): a feature's contribution is its average marginal effect over all orders in which features could be added. For trees there is an exact fast algorithm (TreeSHAP). Contributions add up exactly: base value + Σ SHAP = prediction. Mean |SHAP| over many rows is a global importance that, unlike gain, is in points.",
    formula: "prediction = base value + Σⱼ φⱼ",
    here: "LightGBM's pred_contrib on the mean head.",
    related: ["feature-importance", "base-value", "dependence-plot"],
  },
  {
    id: "base-value",
    term: "Base value (expected value)",
    category: "Explainability",
    short: "The average prediction before looking at this row's features.",
    body: "The starting point of a SHAP waterfall; each feature's SHAP value moves the prediction away from it.",
    related: ["shap"],
  },
  {
    id: "dependence-plot",
    term: "SHAP dependence plot",
    category: "Explainability",
    short: "Feature value vs its SHAP contribution, one dot per row.",
    body: "Shows the shape of a feature's effect: rising dots = higher values push predictions up. Vertical spread at the same value comes from interactions with other features.",
    related: ["shap"],
  },
  {
    id: "correlation",
    term: "Correlation (Pearson r)",
    category: "Explainability",
    short: "How strongly two features move together (−1 … +1).",
    body: "Highly correlated features carry overlapping information; trees will use one or the other almost arbitrarily, which splits importance between them.",
    formula: "r = cov(x, y) / (σx · σy)",
    related: ["feature-importance"],
  },
];

export const GLOSSARY_BY_ID: Record<string, GlossaryEntry> = Object.fromEntries(GLOSSARY.map((g) => [g.id, g]));
