"""phase1 registry and multi-source matches

Revision ID: 0f0a66354678
Revises:
Create Date: 2026-10-02 00:25:42.788763
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0f0a66354678"
down_revision = None
branch_labels = None
depends_on = None

RESOLVED_VIEWS = {
    # consumers read the resolved copy; match.ball_source picks which source's rows that is
    "delivery_resolved": "delivery",
    "innings_resolved": "innings",
    "match_player_resolved": "match_player",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("unique_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_payload",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("url_or_file", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("archive_path", sa.Text(), nullable=True),
        sa.Column("parse_status", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "sha256", name="uq_raw_payload_sha"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "venue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "player_alias",
        sa.Column("player_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "name"),
    )
    op.create_index(
        "ix_player_alias_lower_name",
        "player_alias",
        [sa.literal_column("lower(name)")],
        unique=False,
    )
    op.create_table(
        "player_source_id",
        sa.Column("player_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_key", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "source", "source_key"),
        sa.UniqueConstraint("source", "source_key", name="uq_player_source_key"),
    )
    op.create_table(
        "season",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("competition_id", "year", name="uq_season"),
    )
    op.create_table(
        "season_credits",
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Text(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("credits", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("season", "player_id"),
    )
    op.create_table(
        "team_alias",
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("alias"),
    )
    op.create_table(
        "venue_alias",
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venue.id"],
        ),
        sa.PrimaryKeyConstraint("alias"),
    )
    op.create_table(
        "match",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("cricsheet_id", sa.BigInteger(), nullable=True),
        sa.Column("cricinfo_id", sa.BigInteger(), nullable=True),
        sa.Column("cricbuzz_id", sa.BigInteger(), nullable=True),
        sa.Column("bcci_id", sa.Text(), nullable=True),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("team1_id", sa.Integer(), nullable=False),
        sa.Column("team2_id", sa.Integer(), nullable=False),
        sa.Column("toss_winner_id", sa.Integer(), nullable=True),
        sa.Column("toss_decision", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("win_by_runs", sa.Integer(), nullable=True),
        sa.Column("win_by_wickets", sa.Integer(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("match_number", sa.Integer(), nullable=True),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column("overs", sa.SmallInteger(), nullable=False),
        sa.Column("player_of_match", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("resolved_from", sa.Text(), nullable=False),
        sa.Column("ball_source", sa.Text(), nullable=True),
        sa.Column("data_status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "data_status IN ('single_source', 'unverified', 'verified', 'conflict', 'quarantined')",
            name="ck_match_data_status",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team1_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team2_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["toss_winner_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bcci_id"),
        sa.UniqueConstraint("cricbuzz_id"),
        sa.UniqueConstraint("cricinfo_id"),
        sa.UniqueConstraint("cricsheet_id"),
    )
    op.create_index("ix_match_season_date", "match", ["season_id", "start_date"], unique=False)
    op.create_table(
        "field_conflict",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("innings", sa.SmallInteger(), nullable=True),
        sa.Column("ball_seq", sa.SmallInteger(), nullable=True),
        sa.Column("player_id", sa.Text(), nullable=True),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("source_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'resolved')", name="ck_field_conflict_status"),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "match_id",
            "scope",
            "innings",
            "ball_seq",
            "player_id",
            "field",
            name="uq_field_conflict",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "match_source",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_match_key", sa.Text(), nullable=False),
        sa.Column("raw_payload_id", sa.BigInteger(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("dq_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("status IN ('loaded', 'quarantined')", name="ck_match_source_status"),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["raw_payload.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "source"),
    )
    op.create_table(
        "innings",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("innings", sa.SmallInteger(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("super_over", sa.Boolean(), nullable=False),
        sa.Column("target_runs", sa.Integer(), nullable=True),
        sa.Column("target_overs", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("absent_hurt", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id", "source"],
            ["match_source.match_id", "match_source.source"],
            name="fk_innings_match_source",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "source", "innings"),
    )
    op.create_table(
        "match_player",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("player_id", sa.Text(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("role_in_match", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "role_in_match IN ('xi', 'impact_in', 'impact_out', 'sub', 'sub_fielder')",
            name="ck_match_player_role",
        ),
        sa.ForeignKeyConstraint(
            ["match_id", "source"],
            ["match_source.match_id", "match_source.source"],
            name="fk_match_player_match_source",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "source", "player_id"),
    )
    op.create_index("ix_match_player_player", "match_player", ["player_id"], unique=False)
    op.create_table(
        "delivery",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("innings", sa.SmallInteger(), nullable=False),
        sa.Column("ball_seq", sa.SmallInteger(), nullable=False),
        sa.Column("super_over", sa.Boolean(), nullable=False),
        sa.Column("over", sa.SmallInteger(), nullable=False),
        sa.Column("ball_in_over", sa.SmallInteger(), nullable=False),
        sa.Column("batter_id", sa.Text(), nullable=False),
        sa.Column("bowler_id", sa.Text(), nullable=False),
        sa.Column("non_striker_id", sa.Text(), nullable=False),
        sa.Column("batter_runs", sa.SmallInteger(), nullable=False),
        sa.Column("extras", sa.SmallInteger(), nullable=False),
        sa.Column("total_runs", sa.SmallInteger(), nullable=False),
        sa.Column("extra_type", sa.Text(), nullable=True),
        sa.Column("wides", sa.SmallInteger(), nullable=False),
        sa.Column("noballs", sa.SmallInteger(), nullable=False),
        sa.Column("byes", sa.SmallInteger(), nullable=False),
        sa.Column("legbyes", sa.SmallInteger(), nullable=False),
        sa.Column("penalty", sa.SmallInteger(), nullable=False),
        sa.Column("non_boundary", sa.Boolean(), nullable=False),
        sa.Column("wicket_kind", sa.Text(), nullable=True),
        sa.Column("player_out_id", sa.Text(), nullable=True),
        sa.Column("fielder_ids", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["batter_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bowler_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["match_id", "source", "innings"],
            ["innings.match_id", "innings.source", "innings.innings"],
            name="fk_delivery_innings",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["non_striker_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_out_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "source", "innings", "ball_seq"),
    )
    op.create_index("ix_delivery_batter", "delivery", ["batter_id"], unique=False)
    op.create_index("ix_delivery_bowler", "delivery", ["bowler_id"], unique=False)
    for view, table in RESOLVED_VIEWS.items():
        op.execute(
            f"CREATE VIEW {view} AS SELECT t.* FROM {table} t "
            f"JOIN match m ON m.id = t.match_id AND t.source = m.ball_source"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for view in RESOLVED_VIEWS:
        op.execute(f"DROP VIEW IF EXISTS {view}")
    op.drop_index("ix_delivery_bowler", table_name="delivery")
    op.drop_index("ix_delivery_batter", table_name="delivery")
    op.drop_table("delivery")
    op.drop_index("ix_match_player_player", table_name="match_player")
    op.drop_table("match_player")
    op.drop_table("innings")
    op.drop_table("match_source")
    op.drop_table("field_conflict")
    op.drop_index("ix_match_season_date", table_name="match")
    op.drop_table("match")
    op.drop_table("venue_alias")
    op.drop_table("team_alias")
    op.drop_table("season_credits")
    op.drop_table("season")
    op.drop_table("player_source_id")
    op.drop_index("ix_player_alias_lower_name", table_name="player_alias")
    op.drop_table("player_alias")
    op.drop_table("venue")
    op.drop_table("team")
    op.drop_table("raw_payload")
    op.drop_table("player")
    op.drop_table("competition")
    # ### end Alembic commands ###
